/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = function(knex) {
  return knex('inventory').del()
    .then(function () {

      return knex('inventory').insert([
        { equipment: 'Head Speed Pro Black', count: 9, description: 'Featuring the same specs as the standard version, this sleek black version of the Speed Pro combines the precision of an 18x20 string pattern with a near-perfect balance of speed and stability.  In addition to delivering the connected feel that advanced players crave, the Speed Pro Black packs more than enough spin potential to bring the ball down effectively. Technologies include a uniquely flexible Auxetic construction in the yoke, which is designed to calibrate ball feedback to stroke speed and impact location. As with the previous generation, this update has Graphene 360+, giving it polarized weighting for easier power along with SpiralFibers for better ball feedback. Ultimately, with its precise targeting and exceptional feel, the Speed Pro is a great option for experienced players. The cool black cosmetic is a nice bonus.', user_id: 4 },
        { equipment: 'Asics Court FF 3 Blue Expanse/Koi Men\'s Shoes', count: 2, description: 'The Asics Court FF 3 delivers a speedy feel, glove-like support, and the stability to withstand the most aggressive movements. Designed for one of the most agile players the game has ever seen Novak Djokovic, this update increases the outsole\'s contact area creating a stable landing and reduces the load exerted on the body. The upper hugs the foot like a glove thanks to the mono-sock bootie construction, and is more breathable than before due to a more open mesh under the laces. FlyteFoam under foot feels very responsive and cuts down on weight, while the signature GEL technology absorbs harsh court shock.', user_id: 4 },
        { equipment: 'Head Tour Team 12R Bag Black/Orange', count: 1, description: 'Serious competitors will appreciate all the details that make the Head Tour Team 12 Pack Monstercombi Bag a top contender. Carried by Head\'s top touring pros, this bag features three main compartments which will hold up to 12 racquets, one which has Head\'s Climate Control Technology+ to keep your gear protected from extreme temperatures. The middle compartment is quite large and will hold at least six racquets or can be utilized for your tennis equipment, with an elastic mesh inner pouch for smaller accessories. There is a zippered end pocket, perfect for storing your shoes, in addition to a small exterior accessory pocket on one side of this bag. With padded and adjustable shoulder straps, you can carry this bag as a backpack or use them together as a comfortable over-the-shoulder carrying strap. Take the court in comfort and style with this premium racquet bag from Head! ', user_id: 4 },
        { equipment: 'Babolat Touch VS Natural Gut 17/1.25 String', count: 12, description: 'Babolat\'s top of the line Natural Gut in a thin and responsive 17 gauge. Used by top touring pros and players who demand ultimate feel and control. VS Natural Team Gut is constructed with a tighter gauge tolerance than any previous Babolat VS Natural Gut offering. Includes Thermogut Technology - a process of high temperature finishing that increases the cohesion of the fibers down to the core of the string. Made with BT7 technology which is a new layering structure, increasing durability by 15%. Offers a slightly firmer feel, but remains the "Gold Standard" for comfort and playability.', user_id: 4 },
        { equipment: 'Luxilon ALU Power 16L/1.25 String', count: 12, description: 'TIn addition to being one of the most popular choices on the ATP Tour, this string helped usher in the polyester revolution in tennis. The firm monofilament construction will enable you to take huge cuts at the ball without losing control. As a result, you can generate massive stroke speed, which produces a dangerous combination of pace and spin. Ultimately, this is a great option for intermediate and advanced players who want control, spin and durability. The fact that is offers above average feel for a control string is a very nice bonus.', user_id: 4 },

        { equipment: 'Wilson Pro Staff Six.One 95 v14', count: 2, description: 'Introducing the Pro Staff Six One 95 v14! Like the previous generation, this v14 release delivers all the predictability and directional control that comes when you combine a compact 95 square inch head with a dense 18x20 string pattern. The Pro Staff Six.One 95 also packs a 325 swingweight, giving it just enough stability to absorb and redirect the pace of a big hitter. Technologies include Paradigm Bending, which optimizes the flex between the hoop and shaft to deliver that classic Pro Staff feel. Ultimately, the Six One 95 18x20 is a great option for the experienced player looking for an extremely precise weapon. ', user_id: 1 },
        { equipment: 'Nike Zoom Vapor Cage 4 Rafa Lemon/Bl Men\'s Shoe', count: 1, description: 'If you\'re looking for shoes that meet the demands of your footwork and will turn heads on the court, the Nike Air Zoom Vapor Cage 4 Rafa is for you. It perfectly blends two of Nike\'s most popular tennis shoes. Engineered and designed for one of the best movers on tour (vamos Rafa!), these shoes will meet the standards of players who crave serious support, enhanced stability, ridiculous levels of responsiveness, and maximum durability. A Zoom Air unit in the forefoot offers players more energy as they spring into their next shot. Hard court sliders will appreciate how the outsole has been integrated into the upper where aggressive movers need it most for enhanced durability. Foot frame technology increases stability and reaction time, and in case you needed another reason to get these shoes on your feet, they come backed by a 6-month outsole durability guarantee. Players of all levels who need support and can be hard on their shoes will want to look here before gravitating toward lighter, less durable options.', user_id: 1 },
        { equipment: 'Wilson Noir Tour 12-Pack Bag', count: 1, description: 'The clean styling and different compartments of the Wilson Noir Tour 12-Pack Bag make it a great option for carrying multiple racquets and gear to and from the court. It has two main compartments that can fit up to 12 racquets snugly / 10 comfortably. One compartment is padded and the other has a thermal lining to protect your racquets and strings from the extreme elements. This bag also has a zippered shoe compartment, two zippered accessory compartments on front and on the back for additional court essentials, adjustable padded backpack straps, and grab handles on top and on one end.', user_id: 1 },
        { equipment: 'Luxilon ALU Power 17L/1.20 String', count: 4, description: 'Luxilon Alu Power 1.20 is a thinner version of the world\'s most iconic co-poly, ALU Power 16L/1.25. Our TW playtesters found this 1.20mm version of ALU Power to play a tad softer and with even better feel than the standard 1.25mm version. It also offers massive spin potential and the kind of control that allows big hitters to take full cuts with maximum confidence.', user_id: 1 },

        { equipment: 'Wilson Pro Staff RF97 v13', count: 9, description: 'The Wilson Pro Staff RF97 v13 delivers the classic feel that you expect with tremendous plow through and precision. This update features a design inspired by the classic 1983 Pro Staff but customized for Federer. Legendary inside and out, the Wilson Pro Staff RF97 v13 features a braided graphite layup that is familiar to players that have stayed loyal to the series. The thin beam lets players feel connected to the ball on every shot from any area of the court. Traditionally a heavy weight racquet, the Wilson Pro Staff RF97 v13 weight and swingweight make this a true powerhouse for players that can handle it, with plenty of plow through to put added weight on every shot. Adding a touch of modern spin and control, the 16x19 string pattern bites into the ball effectively while letting you aim for the lines with confidence. an industry standard for the modern player\'s racquet, the Wilson Pro Staff RF97 v13 continues to impress and the new cosmetic combines Roger\'s preferred black paint with the original 1983 Pro Staff lines, but in a custom black, silver and grey striped design. Roger\'s signature in the racquet throat is the final detail to remind you that the Wilson Pro Staff RF97 v13 is an autograph racquet designed and inspired by Federer himself.', user_id: 2 },
        { equipment: 'ON The Roger Pro White/Blue Men\'s Shoes', count: 1, description: 'ON enters the high performance tennis footwear market with the ON The Roger Pro, a design influenced by Roger Federer himself! These shoes are built for the player who can hit all the shots and embodies nimble, balanced movement on the court. Already known for its comfortable yet responsive cushioning with its running shoes, ON carries that over into these premium court shoes, while also focusing on making them very supportive and stable. A unique design feature is the 100% carbon fiber Speedboard located in the midfoot shank region, which gives explosive energy return and also creates a more stable ride. The upper features Engineered Mesh for enhanced breathability and a supportive fit, while the outsole rubber supplies a blend of durability, traction and tread catered to those who slide on the gritty hard courts. ', user_id: 2 },
        { equipment: 'Wilson Noir Tour 12-Pack Bag', count: 1, description: 'The clean styling and different compartments of the Wilson Noir Tour 12-Pack Bag make it a great option for carrying multiple racquets and gear to and from the court. It has two main compartments that can fit up to 12 racquets snugly / 10 comfortably. One compartment is padded and the other has a thermal lining to protect your racquets and strings from the extreme elements. This bag also has a zippered shoe compartment, two zippered accessory compartments on front and on the back for additional court essentials, adjustable padded backpack straps, and grab handles on top and on one end.', user_id: 2 },
        { equipment: 'Wilson Champion\'s Choice Hybrid 16 String', count: 14, description: 'It\'s all in the name. Wilson Champions Choice is a hybrid of two of the most popular strings on tour: Wilson Natural Gut and Luxilon ALU Power Rough. Combining the ultimate playability of a high quality natural gut with the durability, spin and control of a textured polyester gives the player the best of both worlds. For durability and control, use the Luxilon ALU Power Rough in the mains. For a softer feel and playability, use the Wilson Natural Gut in the mains.', user_id: 2 },

        { equipment: 'Babolat Pure Aero Rafa Origin', count: 9, description: 'Introducing the Pure Aero Rafa Origin, the racquet with the closest specifications to Rafa\'s customized racquet. Unlike the standard Pure Aero, the Rafa Origin doesn\'t put any dampening technology between player and ball, giving it the kind of direct ball feedback that advanced players crave. Additional features include Babolat\'s iconic Aeromodular beam and Woofer grommet system. This racquet also comes with a firm 69+RA, providing a crisp, powerful and stable response that has attracted generations of players. What defines the Rafa Origin, however, is its 365+ RDC swingweight, making it very challenging to swing but giving it the needed heft to absorb and redirect the highest levels of pace. The high swingweight offers massive plow through power which is perfect for hitting punishing groundstrokes and serves. The flip side is that ripping heavy spin-loaded angles like Rafa takes additional care with both timing and technique. Those who can leverage this racquet\'s mass will find dangerous levels of pace from the baseline and rock solid stability at net.  In addition to being a great collectible, this is a must buy for those who want to see what it feels like to swing a tour level racquet. Get this rare collectible while supplies last.', user_id: 3 },
        { equipment: 'Babolat Pure Aero Rafa 12 Pack Bag', count: 1, description: 'The Babolat Pure Aero Rafa 12 Pack Tennis Bag has been redesigned and is a great option for tournament players. This large bag is fully waterproof and insulated and can hold up to 12 racquets! With 3 main compartments, you can carry loads of gear and split up your racquets and gear while both sides of the bag offer an exterior accessory pocket. There is an even smaller accessory pocket perfect for dampeners on the top of the bag and a large vented shoe tunnel on the bottom. Newly designed, ergonomic straps are adjustable and padded for easy carrying and this bag will sit up right even when not completely full!', user_id: 3 },
        { equipment: 'Nike Vapor Cage 4 Rafa White/Mango Men\'s Shoe', count: 1, description: 'If you\'re looking for shoes that meet the demands of your footwork and will turn heads on the court, the Nike Air Zoom Vapor Cage 4 Rafa is for you. It perfectly blends two of Nike\'s most popular tennis shoes. Engineered and designed for one of the best movers on tour (vamos Rafa!), these shoes will meet the standards of players who crave serious support, enhanced stability, ridiculous levels of responsiveness, and maximum durability. A Zoom Air unit in the forefoot offers players more energy as they spring into their next shot. Hard court sliders will appreciate how the outsole has been integrated into the upper where aggressive movers need it most for enhanced durability. Foot frame technology increases stability and reaction time, and in case you needed another reason to get these shoes on your feet, they come backed by a 6-month outsole durability guarantee. Players of all levels who need support and can be hard on their shoes will want to look here before gravitating toward lighter, less durable options.', user_id: 3 },
        { equipment: 'Babolat RPM Blast 15L/1.35 String', count: 10, description: 'Rafael Nadal\'s string of choice is the thickest and most durable version of RPM Blast. This co-poly string is also very, very spin friendly. The slick surface of RPM Blast allows the main strings to slide out of alignment, grab the ball and then snap back to add spin to the shot. While all co-poly monofilaments do this to some extent, our lab tests confirm that RPM Blast is exceptional in this regard. Though RPM Blast offers a slightly softer feel than traditional polyesters, it is by no means the softest co-poly available. It is an ideal choice for big hitters with heavier racquets seeking maximum control, durability, and spin. (And it seems to be working quite well for Rafa!)', user_id: 3 },
      ]);
    });
};
